### ISSUE TITLE
Timestamp nanoseconds may not be set properly

### ISSUE THREAD

**Issue by trey0** [nasa/astrobee_android#24]
I don't think these two lines are consistent [1]. If `mCaptureCompleteTimestamp` has units of milliseconds, then we should multiply by 1000000 to get nanoseconds (instead of 1000).

[1] https://github.com/nasa/astrobee_android/blob/a8560ab0270ac281d8eadeb48645f4224582985e/guest_science_projects/sci_cam_image/app/src/main/java/gov/nasa/arc/irg/astrobee/sci_cam_image/CameraController.java#L371

**Comment by oleg-alexandrov** [comment]
What is called here 'nsecs' is not nanoseconds. If a time in seconds is
9.123, then nsecs, as defined in the code,  is 123.

That is per the code:

long secs = mCaptureCompleteTimestamp/1000;
long nsecs = (mCaptureCompleteTimestamp % 1000) * 1000;

Here, mCaptureCompleteTimestamp = 9123, as it is time in milliseconds.

There is a bug here, however. If the time is 9.012, then nsecs will be
defined as 012 which is 12. However, when the time string is put back
together, it is done as:

String timestamp = String.format("%d.%d", secs, nsecs);

which will create the number 9.12, and not the original 9.012.

I dug up my old sci cam code and the bug is there too. Likely this was
inherited from my code. I don't recall how I came up with that logic.

So a bugfix is needed. It may be simpler to do like in C++, where the time
is always a double, in seconds, and when it comes to making a file the
following code is used:

 snprintf(filename_buffer, sizeof(filename_buffer), "%10.7f.jpg",
curr_time);

Or, this may work:

String.format("%d.%03d", secs, nsecs)

and one should rename nsecs to msecs, so mili-seconds.

**Comment by trey0** [comment]
@oleg-alexandrov Thanks for your comments. I think it is slightly more involved to fix because the `secs` and `nsecs` are used in more than one place. Here is one approach that seems sufficient to me:

1. Change so `nsecs` actually has nanosecond units, since that is what is expected in the rosjava `Time` constructor called by `publishImage()` below:
```
long nsecs = (mCaptureCompleteTimestamp % 1000) * 1000;
```
->
```
long nsecs = (mCaptureCompleteTimestamp % 1000) * 1000000;
```

2. Change the image filename generating code to properly format nanoseconds so the filename can be interpreted as a floating point number of seconds:
```
String timestamp = String.format("%d.%d", secs, nsecs);
```
->
```
String timestamp = String.format("%d.%03d", secs, nsecs / 1000000);
```

However, I would be happy however @kbrowne15 wants to approach it.

**Comment by kbrowne15** [comment]
@trey0 Yeah, I was thinking of doing something similar to that.

**Comment by kbrowne15** [comment]
Fixed in https://github.com/nasa/astrobee_android/pull/25
