### ISSUE TITLE
Turning ON/OFF payload bays.

### ISSUE THREAD

**Issue by erobinson-mei** [nasa/astrobee_android#51]
I am working on a project involves developing an Astrobee payload, and I am wondering how to turn on/off the payload bays and check the status. I looked through the repository source code and found the following definition, but there aren't any examples that use it. How do I operate the payloads?

```java
// Copyright 2017 Intelligent Robotics Group, NASA ARC

package gov.nasa.arc.astrobee.types;

public enum PoweredComponent {
    LASER_POINTER("Laser Pointer"),
    PAYLOAD_TOP_AFT("Payload Top Aft"),
    PAYLOAD_BOTTOM_AFT("Payload Bottom Aft"),
    PAYLOAD_BOTTOM_FRONT("Payload Bottom Front"),
    PMC("PMC");

    private final String m_value;

    PoweredComponent(final String value) {
        m_value = value;
    }

    @Override
    public String toString() {
        return m_value; 
    }
}
```

**Comment by marinagmoreira** [comment]
In the procedures we have these commands (`pay_ta` is for top aft, and you change that accordingly to which payload you are trying to activate):
````
eps_driver_tool -power -set on pay_ta
eps_driver_tool -power -set off pay_ta
````

**Comment by erobinson-mei** [comment]
Are types of commands are those? What device is executing them?

**Comment by marinagmoreira** [comment]
we run it in the robot's LLP, here is the tool code https://github.com/nasa/astrobee/blob/master/hardware/eps_driver/tools/eps_driver_tool/eps_driver_tool.cc

**Comment by rgarciaruiz** [comment]
Yes, we usually handle this via procedures, not programmatically. But if for some reason you really need to this from your APK then you can use the `Power.powerOnItem` from the [command dictionary](https://nasa.github.io/astrobee/v/develop/command_dictionary.html).

We don't use this command very often, so in case you have issues with it, you can probably explore calling the service directly: `/hw/eps/configure_payload_power`.

In order to get the status you're best bet is probably subscribing to `/hw/eps/power_state`.

Again, we usually handle this manually via procedures/scripts, since it reduces points of failure for your APK, but I thought you should know this option exists as well.

**Comment by erobinson-mei** [comment]
Thank you. I was looking for this type of functionality, but I want to use the recommended options for ease-of-use and reliability.
