### ISSUE TITLE
Sending Large Files to Ground

### ISSUE THREAD

**Issue by erobinson-mei** [nasa/astrobee_android#54]
Is it possible to send larger files to ground stations? I was looking through the guest science manager for a way to send files, but the functions in the `StartGuestScienceService` class only allow messages under 2kB.

```java
    public void sendMsg(MessageType type, String topic, byte[] data) {
        if (!this.mBound) {...} 
        else if (data.length > 2048) {
            throw new RuntimeException("Data passed to sendData function is too big to send to ground. Must be 2K.");
        } else {...}
    }
```

**Comment by rgarciaruiz** [comment]
The function `sendData` in fact has that limitation. The content of that message is sent to the `/gs/data` topic and then to the ground via RTI DDS, where it can only be read by tools able to receive this "real-time" telemetry (like our Ground Data System graphical interface). 

If you produce more data, you could save it to a file in the designed folder for your APK (more info [here](https://github.com/nasa/astrobee_android/blob/master/guest_science_readme.md#directory-structure)), then we can download it for you at the end of the activity.

Do you really need to send data larger than 2K in real time? Or is saving to a file acceptable?

**Comment by erobinson-mei** [comment]
We anticipate users/engineers will want to download files from our payload to analyze the data in post. We plan on using guest science commands to send a list of the files, then users may use a separate command to download the file. The files can be downloaded at the end of an activity, but the guest science app may need to retrieve a list of files longer than 2K characters.

**Comment by rgarciaruiz** [comment]
I assume you expect to generate many files then? How are they organized? How big are they? Are they staying forever in your payload? Are you only downloading selected files or do you want all data from an activity/test?

I suppose you could send only the most recent filenames (or the latest test) in one message or send several messages down, or request a range/date. You may also want to consider readability. During ISS ops it can be difficult to navigate a lot of data (file names in this case) in order to take a quick decision. You can always save a full filename list to the HLP for history purposes.

I am not familiar with the file structure you have in mind, but you might want to consider some form of data condensation (e.g. directories).

**Comment by erobinson-mei** [comment]
Thank you for all of your suggestions. I understand why sending large amounts of data using `sendData()` would be a bad idea. The large number of files is more of an edge-case if the user doesn't delete files, or if the payload is in unsupervised operation for extended periods of time. I will go ahead and close this issue and figure out a way round the 2kB limit.
